### ISSUE TITLE
Client is and client secret key

### ISSUE THREAD

**Issue by hareshlad** [MapmyIndia/mapmyindia-interactive-map-js-api#2]
Hello,
Where can I find client ID and Client secret key in mapmyindia account.I can see API key and OAuth key in my account

**Comment by kunalbharti** [comment]
oAuth set of keys consists of a client ID and client secret.
These can be used to generate access tokens which can be used in place of static API keys in all of MapmyIndia APIs, providing an additional layer of security.
They will be available on the same dashboard which shows your other API key (static keys)
